### ISSUE TITLE
API doesn't seems to work

### ISSUE THREAD

**Issue by LiliGuimaraes** [bezzocoaline/theblackwomenhistory-api#1]
I trying to use this API, to make REPROGRAMA exercises, and then, nothing appears running this repo like are here.

**Comment by alinebezzoco** [comment]
Hi, @LiliGuimaraes! :) 

Did you use this url to GET all infos? https://theblackwomanhistory.firebaseio.com/.json 
I tested in Postman and returns 200 OK. 

Could you to test the API again?  
If this error persists, please describe in details the API problem.
